version: "3"

services:
  traefik:
    image: traefik
    command: --api --docker
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.dev.local"
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

networks:
  web:
    external: true
