# see https://docs.traefik.io/v1.0/toml/
debug=true
loglevel = "DEBUG"
defaultEntryPoints = ["http", "https", "ws", "wss"]
InsecureSkipVerify = true

[api]
address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
domain = "dev.local"

# Force HTTPS
[entryPoints]
  [entryPoints.http]
    address = ":80"
#  [entryPoints.https]
#    address = ":443"
#    [entryPoints.https.tls]
#      [[entryPoints.https.tls.certificates]]
#      certFile = "/etc/traefik/traefik.crt"
#      keyFile = "/etc/traefik/traefik.key"

# Let's encrypt configuration
#[acme]
#  email = "user@example.com"
#  storage = "/etc/traefik/acme.json"
#  entryPoint = "https"
#  acmeLogging = true
#  OnHostRule = true